version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "%(asctime)s - %(module)s - %(funcName)s - %(levelname)s: %(message)s"
        file_fmt:
            format: "%(asctime)s - %(module)s - %(funcName)s - line:%(lineno)d - %(levelname)s - %(message)s"
handlers:
    console_handler:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: file_fmt
            filename: logs/info.log
            maxBytes: 10485760
            backupCount: 5
            encoding: utf8
    debug_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: file_fmt
            filename: logs/debug.log
            maxBytes: 10485760
            backupCount: 5
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: file_fmt
            filename: logs/errors.log
            maxBytes: 10485760
            backupCount: 5
            encoding: utf8
loggers:
    console:
             level: DEBUG
             handlers: [console_handler,]
             propagate: no
root:
    level: DEBUG
    handlers: [console_handler,info_file_handler,error_file_handler,debug_file_handler]